### ISSUE TITLE
Create 1.0.10 release

### ISSUE THREAD

**Issue by nhamiltontt** [springml/salesforce-wave-api#11]
Can we cut a 1.0.10 release with the queryAll functionality? I'd like to submit a patch to expose queryAll as an option in the [spark-salesforce](https://github.com/springml/spark-salesforce) library, and need to reference an updated version of this library for that.

**Comment by samuel-pt** [comment]
Triggered release of 1.0.10. Will be available in maven repository in few hours

**Comment by nhamiltontt** [comment]
Thank you!
